### ISSUE TITLE
Vue Router development assistance

### ISSUE THREAD

**Issue by dniccum** [mattrothenberg/vue-flip-toolkit#16]
Hi I am currently in the process of trying to implement this package into a Chat Box that I currently building. I have attempted to use this in both a router and non-router environment with no luck unfortunately. Not sure if my key's or id's are off, or I am just missing the boat completely.

If you have a second to tell me what I'm doing wrong, I would appreciate it.

## Simple

This is a simple implementation that I have built that I cannot get to work:

```vue
<template>
    <Flipper :flipKey="key">
        <Flipped flipId="btn-chat-launch" scale v-if="!visible">
            <chat-launch-button @click="showChat"></chat-launch-button>
        </Flipped>
        <Flipped flipId="btn-chat-launch" scale v-else>
            <chat-wrapper></chat-wrapper>
        </Flipped>
    </Flipper>
</template>

<script>
    import { EventBus } from '../../EventBus';
    import { Flipper, Flipped } from 'vue-flip-toolkit';
    import ChatLaunchButton from "./ChatLaunchButton";
    import ChatWrapper from "./ChatWrapper";

    export default {
        name: "Chat",
        components: {
            ChatLaunchButton,
            ChatWrapper,
            Flipper,
            Flipped,
        },
        data() {
            return {
                visible: true
            }
        },
        mounted() {
            EventBus.$on('hideChat', () => {
                this.visible = false;
            })
        },
        beforeDestroy() {
            EventBus.$off('hideChat');
        },
        computed: {
            key() {
                return this.visible.toString();
            }
        },
        methods: {
            showChat() {
                this.visible = true;
            }
        }
    }
</script>
```

## Router

This is the router implementation that I cannot get to work either:

### wrapper

```vue
<template>
    <div class="chat-wrapper shadow">
        <Flipper :flipKey="key" stagger="gentle" className="d-flex flex-column flex-1">
            <router-view></router-view>
        </Flipper>
    </div>
</template>

<script>
    import { Flipper } from 'vue-flip-toolkit';
    export default {
        name: "ChatWrapper",
        components: {
            Flipper,
        },
        beforeCreate() {
            this.$router.push('/')
        },
        computed: {
            key() {
                return this.$route.path;
            }
        }
    }
</script>
```

### home

```vue
<template>
    <div class="chat-page">
        <chat-header>
            <button @click="hideChat" class="chat-header-button text-white bg-transparent border-0 "><i class="fa fa-bars" aria-hidden="true"></i></button>
            <i class="fa fa-comment mr-2 font-size-large" aria-hidden="true"></i>
            <span class="font-size-small">Chats</span>
        </chat-header>
        <section class="chat-list px-3">
            <div class="chat-list-heading">
                Recent Conversations
            </div>

            <Flipped v-for="conversation of conversations" :key="conversation.id" :flipId="conversations.slug">
                <chat-conversation-card :conversation="conversation" @click="viewConversation(conversation.slug)"></chat-conversation-card>
            </Flipped>

        </section>
    </div>
</template>

<script>
    import { EventBus } from '../../EventBus';
    import { Flipped } from 'vue-flip-toolkit';
    import ChatHeader from "./ChatHeader";
    import ChatConversationCard from "./ChatConversationCard";

    export default {
        name: "ChatIndex",
        components: {
            ChatConversationCard,
            ChatHeader,
            Flipped,
        },
        data() {
            return {
                conversations: [
                    {'id': 1, 'slug': 'abc'},
                    {'id': 2, 'slug': 'def'},
                ]
            }
        },
        methods: {
            hideChat() {
                EventBus.$emit('hideChat');
            },
            viewConversation(slug) {
                this.$router.push(`/conversations/${slug}`);
            }
        },
    }
</script>
```

### detail

```vue
<template>
    <Flipped scale translate :flipId="flipId">
        <div class="chat-page">
            <chat-header>
                <router-link to="/" class="chat-header-button text-white bg-transparent border-0"><i class="fa fa-bars" aria-hidden="true"></i></router-link>
                <span class="font-size-small">Chats</span>
            </chat-header>
            <section class="chat-list px-3">

            </section>
        </div>
    </Flipped>
</template>

<script>
    import ChatHeader from "./ChatHeader";
    import { Flipped } from 'vue-flip-toolkit';

    export default {
        name: "ChatConversation",
        components: {
            ChatHeader,
            Flipped
        },
        computed: {
            flipId() {
                return this.$route.params.conversation;
            },
        }
    }
</script>
```

**Comment by mattrothenberg** [comment]
Hi, do you mind putting this in a CodeSandbox?

Thanks!

**Comment by dniccum** [comment]
Here is the CodeSandbox: https://codesandbox.io/s/vue-template-1pj6t

The "simple" instance that I am referring to is in the "Chat" component.

The router instance is in the ChatWrapper, ChatIndex, and ChatConversation components.

**Comment by mattrothenberg** [comment]
This one is super interesting. I have a theory as to why your code isn't working, though.

I noticed that in all of my examples, the `Flipped` components were wrapping plain old HTML nodes, e.g.,
```vue
<Flipped flipId="foo">
  <div class="foo">Foo</div>
</Flipped>
```

In your examples, however, the `Flipped components` are wrapping actual Vue components, e.g.,
```vue
<Flipped :flipId="key">
  <chat-button />
</Flipped>
```

In the [React Flip Toolkit docs](https://github.com/aholachek/react-flip-toolkit#wrapping-a-react-component), the author Alex calls out having to use React's "render props" API to ensure that the rendered child receives all of the right attributes from the Flip library, such that a transition can occur. These attributes – namely the inline styles – are missing from your examples, and hence the lack of transition.

My suggestion – and I _think_ it will work, as I just did a quick experiment on my end – is to change your markup such that the `Flipped` instances live _inside_ your custom components, not _outside_ as they currently do. So, you end up with something like this –

```vue
<!-- Chat.vue (OLD WAY) -->
<Flipped :flipId="key" v-if="!visible">
  <chat-button />
</Flipped>
```

```vue
<!-- Chat.vue (NEW WAY)  -->
<chat-button v-if="visible" />
```

```vue
<!-- ChatButton.vue (NEW WAY) --> 
<template>
  <Flipped :flipId="key" v-if="!visible">
    <div>Button markup goes here</div>
  </Flipped>
</template>
```

Let me know if this does the trick. I can't tell whether I need to go back to the drawing board on this one so support this pretty common use case.

**Comment by dniccum** [comment]
Thanks a bunch for the feedback. I have made the requested updates. I think we are making progress. The button that shows and minimizes the chat window works like a charm. However for the life of me, I have not been able to get the router to work.

I have updated the sandbox accordingly: https://codesandbox.io/s/vue-template-1pj6t

**Comment by mattrothenberg** [comment]
I don't fully understand what's not working. 

When you say "the router," what do you mean? What animation or general behavior do you expect to see that isn't working?

**Comment by dniccum** [comment]
Sorry, I should have been clearer. The router itself works fine, but the transitions from index page to the child pages are not working.

**Comment by mattrothenberg** [comment]
No worries. I cooked up a rough CodeSandbox illustrating how I might go about building such a 
UI. Note that the transitions themselves are _super_ rough, and you'd definitely need to go back and add `inverseFlipId`s to ensure that the right elements are transitioning into place. Alex (the author of `react-flip-toolkit` does a great job of explaining how this works in her README.

https://codesandbox.io/s/vue-template-qw928

**Comment by mattrothenberg** [comment]
@dniccum Can I close out this issue?

**Comment by dniccum** [comment]
@mattrothenberg Sorry that I didn't get back to you. Yes this approach seemed to have fixed a lot of my issues.  I need to clean up some of the animations with the available event listeners but you have put me on the right track. Thanks for your help.

**Comment by mattrothenberg** [comment]
@dniccum No problem. Good luck!

**Comment by kedrzu** [comment]
I've just digged through this issue and it helped me a lot with my project as well!
@mattrothenberg I think you should emphase this in docs, because it's really valuable info!

**Comment by mattrothenberg** [comment]
@kedrzu Glad it helped. Feel free to add something to the README so that others can take advantage of that knowledge!
