### ISSUE TITLE
Can staggerConfig props be reactive ?

### ISSUE THREAD

**Issue by Grafikart** [mattrothenberg/vue-flip-toolkit#17]
Hi,

I'm getting a problem and I was wondering if you think it can be solved without too much work.

I have this computed property

```js
  computed: {
    staggerConfig () {
      return {
        listItem: {
          reverse: this.active !== 0,
          speed: 1
        }
      }
    }
  }
```

used this way 

```html
  <Flipper
          :flipKey="active"
          :staggerConfig="staggerConfig"
    >
   // ....
</Flipper>
```

Unfortunately, the props staggerConfig only use the first value of staggerConfig and is never reversed. If we want to change the behaviour we have to mutate the object.

```js
    onClick (item) {
      this.active = this.active === item ? 0 : item
      this.staggerConfig.listItem.reverse = this.active !== 0
    },
```

My fix would be to watch staggerConfig here https://github.com/mattrothenberg/vue-flip-toolkit/blob/master/src/Flipper.vue#L82 and update Flipper instance accordingly. Unfortunately i'm not familiar enough with Flipper to handle a PR :(

**Comment by Grafikart** [comment]
You can see the problem on this story : https://keen-davinci-e49eba.netlify.com/?path=/story/examples--accordion , the stagger is never reversed

**Comment by mattrothenberg** [comment]
Hey, thanks for raising this issue @Grafikart. I've done a little bit of investigation, but don't have any immediate solutions.

1. Good catch re: `staggerConfig` not being reactive. We _should_ be able to fix this like you said, by adding a watch statement to `Flipper` and setting the new stagger config value on `this.flipInstance`.

```vue
staggerConfig(oldConfig, newConfig) {
  if (oldConfig !== newConfig) {
    console.log("staggerConfig change");
    this.flipInstance.staggerConfig = newConfig;
  }
}
```
That said, I did try that change and nothing seemed to update, so I think there might be something else going on.

I'll dig into this today. In the meantime, feel free to clone this repo, `yarn && yarn storybook` – you can modify the `Flipper.vue` and `Flipped.vue` source while you tinker with the stories, so there's a really nice feedback loop.

**Comment by mattrothenberg** [comment]
@Grafikart Should be resolved by https://github.com/mattrothenberg/vue-flip-toolkit/pull/18.

Published in `1.6.0`. Let me know!

**Comment by Grafikart** [comment]
Sorry for my lack of feedback :(

It works perfectly now. Thanks !

**Comment by mattrothenberg** [comment]
@Grafikart pas de soucis
