### ISSUE TITLE
Examples: Isn't it better to have props in kebab-case?

### ISSUE THREAD

**Issue by v-stein** [mattrothenberg/vue-flip-toolkit#19]
Hi,

The examples in the docs are showing `flipKey`, `flipId` and other props usage whose names are all written in `camelCase`.

According to this Vue.js style guide [discussion](https://github.com/vuejs/vuejs.org/pull/1160#discussion_r142002772), shouldn't it be in `kebab-case`?

**Comment by mattrothenberg** [comment]
Pull requests are welcome if you're interested in bringing the API of this component closer to what's described in the Vue styleguide!
