### ISSUE TITLE
Flex-direction can't be animated

### ISSUE THREAD

**Issue by Sufhal** [mattrothenberg/vue-flip-toolkit#24]
Hi, it seems to be impossible to animate `flex-direction` property. Should-it ?
How am I supposed to do that vertical/horizontal transition ?

**Little codesandbox example** 👇
https://codesandbox.io/s/suspicious-lichterman-cy7ju?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fcomponents%2FFlippedElement.vue&theme=dark

**Comment by mattrothenberg** [comment]
A couple of things –

1. I'm not sure I understand the animation you're even going for. Do you have a video walkthrough of the intended outcome?
2. This likely wouldn't have anything to do with `vue-flip-toolkit`, but rather its parent library `flip-toolkit`.
3. To clarify, your example is 100% animating. It's just that you haven't applied inverse transitions to the inner elements, hence the jank.

**Comment by Sufhal** [comment]
Unfortunately I havn't any video to show you, I modified a bit the sandbox : [https://codesandbox.io/s/vue-flip-toolkit-flex-properties-test-he2e1?fontsize=14&hidenavigation=1&theme=dark](Codesandbox)

I wish they'd put themselves (`div.A` & `div.B`) `width: 50%` : not animated
Moving `div.B` from `left: 50%` to `left: 0%` : not animated

What am I doing wrong here ?

**Comment by mattrothenberg** [comment]
@Sufhal I'm honestly not too sure, but I don't think this is an issue with `vue-flip-toolkit`. I wonder if this could be solved with some kind of imperative animation library like Greensock/Tweenmax.
