### ISSUE TITLE
Unexpected behavior when using display: fixed;

### ISSUE THREAD

**Issue by dasmikko** [mattrothenberg/vue-flip-toolkit#31]
I'm trying to use vue-flip-toolkit to make a nice transition, from element to a floating dialog.

The main div transitions fine, but the content suddenly jumps out of the main container. 

Here is an example showcasing the issue:
https://codesandbox.io/s/fervent-paper-0xzf8?fontsize=14&hidenavigation=1&theme=dark

**Comment by mattrothenberg** [comment]
Hi @dasmikko – 

I think there's likely an issue with your markup, as things should work fine with `position: fixed;`. Here's an example for you to look at.

![Kapture 2020-10-04 at 08 41 56](https://user-images.githubusercontent.com/5148596/95015893-99422800-061d-11eb-9c17-332607381c46.gif)

https://codesandbox.io/s/condescending-oskar-jyiw9?file=/src/App.vue

**Comment by dasmikko** [comment]
Huh, this is interesting. The issue goes away when I remove the `transform: translate(-50% -50%)`

So my dialog css goes from:
```
position: fixed;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```
to this
```
position: fixed;
top: 50%;
left: 50%;
```

I'm not sure if the reason is because of my markup, as using transform: translate isn't something hacky.

**Comment by mattrothenberg** [comment]
@dasmikko Interesting. Again, because `vue-flip-toolkit` is a wrapper around `flip-toolkit` and doesn't have strong opinions about positioning, I'm reticent to classify this as a bug or issue.

**Comment by dasmikko** [comment]
@mattrothenberg Totally fair. I don't think the issue makes sense, like you stated, the library doesn't care about positioning.

Like, it literally just applies the end styling, and transitions between it.

I'm just totally clueless what to do from here.

**Comment by mattrothenberg** [comment]
If you can provide a mock-up of what you're going for (I can't really make
sense of your initial code sandbox) I'd be happy happy to try to re-create
it for you.

**Comment by dasmikko** [comment]
The main idea is, i have a list of notes, where they have a title, and a preview of the note content. Once you click on the note, it will expand to a dialog filling most of the screen. I want the transition to me as seamless as possible.

After experimenting with a bunch of things, I tried positioning the dialog container, with flexbox instead, which worked far better!
https://codesandbox.io/s/heuristic-margulis-jt651?fontsize=14&hidenavigation=1&theme=dark

Now i'm just trying to make the header text not stretch on transition.

PS: Fantastic library btw!

**Comment by mattrothenberg** [comment]
Excellent, glad you got it sorted. Closing this issue for the time being!
